version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/opencontainers/runc
    steps:
      - checkout
      - setup_remote_docker
      - run: apt-get update && apt-get install -y libseccomp-dev
      - run: make
      - store_artifacts:
          path: runc
          destination: runc
workflows:
  version: 2
  do-it:
    jobs:
      - build
